version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: algoakhada-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: algoakhada
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - algoakhada-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d algoakhada"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  algoakhada-network:
    driver: bridge

volumes:
  postgres-data:
