version: '3.8'

services:
  redis:
    image: redis:latest # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port (host:container)
    volumes:
      - redis_data:/data # Persist Redis data to a volume
    restart: always # Automatically restart the container if it stops

volumes:
  redis_data: # Define a volume for Redis data persistence